# Site
repository: https://github.com/ksm0517/ksm0517.github.io/resume/
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: ê¹€ì„±ë¯¼
title: AI Engineer
email: 7tkfkd@naver.com
# email_title: Email (Email title override)
phone: 010-4879-7216
# phone_title: Phone (Phone title override)
website: https://blog.naver.com/7tkfkd
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  ksm0517
# stackoverflow_username: "00000001"
facebook_username: ksm0517
# googleplus_username: +jekyll

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ìš´ë™ê³¼ ì§€ì  í–¥ìƒì„ ê±°ë“­í•˜ëŠ” í”„ë¡œê·¸ë˜ë¨¸ <mark>ìš´í”„ì…ë‹ˆë‹¤.</mark>.<br/>
  ì·¨ë¯¸ë¡œ ì¼ë ‰ê¸°íƒ€ğŸ¸ë¥¼ ì¹©ë‹ˆë‹¤. íŠ¹ê¸°ëŠ” ì˜ìƒ í¸ì§‘ğŸ¬ì…ë‹ˆë‹¤.ğŸ¥<br/>
  ëŒ€í•™êµ ë•Œ ì‘ì›ë‹¨ì¥, ê³¼ëŒ€í‘œâ¤ï¸â€ğŸ”¥ ë“±ì„ ë§¡ì•„ íŒ€ì›ë“¤ê³¼ ì†Œí†µ, ì„±ê³¼ë¬¼ì„ ë§Œë“œëŠ” ê²ƒì˜ ì¦ê±°ì›€ì„ ë°°ì› ìŠµë‹ˆë‹¤.<br/>
  ë¹„ì „ê³µìë¡œì¨ CSì§€ì‹ì´ ë¶€ì¡±í•œ ì ì„ ì±„ìš°ê³ ì í‹ˆí‹ˆíˆ ìš´ì˜ì²´ì œ, ìë£Œêµ¬ì¡°, ì•Œê³ ë¦¬ì¦˜ ë“±ì— ëŒ€í•´ ê³µë¶€í•˜ê³  ìˆìŠµë‹ˆë‹¤.âœï¸<br/>
  ë¶ˆí¸í•¨ì´ ìˆëŠ” ê³³ì— ë¶ˆí¸í•¨ì„ ì—†ì• ëŠ”, ìƒì‚°ì„±ì„ í–¥ìƒì‹œí‚¤ëŠ” í”„ë¡œê·¸ë¨ì„ ê°œë°œí•˜ê³  ì‹¶ìŠµë‹ˆë‹¤.ğŸ˜ƒ

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: classification
        link: https://github.com/ksm0517/portfolio/tree/main/classification
        link_text: report Link
        additional_links:
          - title:  https://github.com/boostcampaitech2/image-classification-level1-33
            icon: fab fa-github
            url: https://github.com/boostcampaitech2/image-classification-level1-33
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          gender, mask, age classifcation task
        description: | # this will include new lines to allow paragraphs
          <mark>contribute</mark> : customizing label smoothing loss, psuedo labeling and management schedule.<br/>
          <mark>result</mark> : increse 0.1 f1 score by my contribute <br/>
          Studied all pipeline of AI model like dataset, data loader, train, evaluation and so on.

      - layout: left
        title: object detection
        link: https://github.com/ksm0517/portfolio/tree/main/object_detection
        link_text: report Link
        additional_links:
          - title:  https://github.com/boostcampaitech2/object-detection-level2-cv-07
            icon: fab fa-github
            url: https://github.com/boostcampaitech2/object-detection-level2-cv-07
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          trash data detection task and also classification too
        description: | # this will include new lines to allow paragraphs
          <mark>contribute</mark> : visualize, universe101, pvt-B3, DCN, swin, ensemble etc.<br/>
          <mark>result</mark> : increase 0.1 f1 score with experiment <br/>
          I found when model become deeper, it makes high mAP
          I thought it might not helpful for me to experimenting just bigger model.
          So I focused on finding trouble in visualized picture.
          And tried fix them by changing function of model like rpn proposal, fpn.
          
      - layout: left
        title: segmentation
        link: https://github.com/ksm0517/portfolio/tree/main/segmentation
        link_text: report Link
        additional_links:
          - title:  https://github.com/boostcampaitech2/semantic-segmentation-level2-cv-07
            icon: fab fa-github
            url: https://github.com/boostcampaitech2/semantic-segmentation-level2-cv-07
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          trash data segmentation task and also classification too
        description: | # this will include new lines to allow paragraphs
          <mark>contribute<mark> : build lib environment, ensemble, augmentation, crf tool etc.<br/>
          <mark>result</mark> : rank 14 -> 9, increase 0.03 mIoU with experiment <br/>
          I tried to see change when augmentation is applied.
          I think this was the reason that we could go high when private set was revealed.
          And I tried to make many engineering tool. 


  - title: Education
    layout: list
    content:
      - layout: right
        title: Myongji Univ.
        sub_title: BA Physic
        caption: 2015~2019
        # quote: >
        #   Studied physics, math, semiconductor and also studied computational physics
        # description: | # this will include new lines to allow paragraphs
        #   Now, I actually like physics too. but I like computational things more than physics 

      - layout: right
        title: boostcamp
        sub_title: camper
        caption: August 2021 ~ present
        link: https://boostcamp.connect.or.kr/
        link_text: site Link
        quote: >
          Study AI
        description: | # this will include new lines to allow paragraphs
          Basic AI, classification, object detection, segmentation, Model optimization, product serving

  - title: Extra curricular
    layout: list
    content:
      - layout: right
        title: cheer team
        sub_title: member -> leader
        caption: march 2015 ~ october 2016
        quote: >
          ë¦¬ë”ë¡œì¨ì˜ ì„±ì¥
        description: | # this will include new lines to allow paragraphs
          ì˜¤í•´ê°€ ìŒ“ì¸ ê´€ê³„ì— ì‹œí–‰ì°©ì˜¤ë¥¼ ê²ªìœ¼ë©°, íŒ€ì›ë“¤ê³¼ í˜‘ì—…í•˜ëŠ” ë°©ë²•ì„ ìµí˜”ìŠµë‹ˆë‹¤. <br/>
          ë¶ˆí¸í•œ ê´€ê³„ì—ì„œ ë„ë§ì¹˜ì§€ ì•Šê³  í•´ê²°í•¨ìœ¼ë¡œì¨ ì±…ì„ê°ì„ ë°°ì› ìŠµë‹ˆë‹¤.

      - layout: right
        title: broadcast team
        sub_title: member -> manager
        caption: January 2015 ~ present
        link: https://www.youtube.com/channel/UC_PGmoXPG9V0B14Bpeotp1w
        link_text: site Link
        quote: >
          ì‹¤ì‹œê°„ ë°©ì†¡ì„ ì§„í–‰í•˜ê³  í¸ì§‘
        description: | # this will include new lines to allow paragraphs
          ëª¨ë¥´ëŠ” ì¼ë„ ìœ íŠœë¸Œ, êµ¬ê¸€ë§, ì•„ëŠ” ë¶„ë“¤ê»˜ ì§ˆë¬¸ ë“±ì„ í†µí•´ í•™ìŠµí–ˆìŠµë‹ˆë‹¤. <br/>
          íŠ¹ë³„íˆ ì˜ìƒì„ í¸ì§‘í•˜ëŠ” ê³¼ì •ì—ì„œ ë§ˆìŠ¤í‚¹ì„ ì§ì ‘ ìˆ˜ì‘ì—…ìœ¼ë¡œ í•˜ëŠ” ë°, ì´ë¥¼ ì¸ê³µì§€ëŠ¥ìœ¼ë¡œ ìˆ˜í–‰í•  ìˆ˜ ìˆë‹¤ë©´ ì¢‹ê² ë‹¤.<br/>
          ë¼ëŠ” ìƒê°ì„ í•œ ì ì´ ìˆìŠµë‹ˆë‹¤.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      **anormaly detection, mlops** ë“±ì— ê´€ì‹¬ì„ ê°€ì§€ê³  ìˆìœ¼ë©°, AI ì—°êµ¬ í™˜ê²½ êµ¬ì¶•ì— í¥ë¯¸ë¥¼ ëŠë‚ë‹ˆë‹¤.<br/>
      **ì˜ ëª°ë¼ì„œ í•´ë§¤ëŠ” ê²ƒì„ ë‘ë ¤ì›Œ í•˜ì§€ ì•Šìœ¼ë©°**, ì €ë³´ë‹¤ ì˜ ì•„ëŠ” ë¶„ì—ê²Œ ë°°ìš°ëŠ” ê²ƒì— ì¦ê±°ì›€ì„ ëŠë‚ë‹ˆë‹¤.<br/>
      í”„ë¡œì íŠ¸ë¥¼ ìˆ˜í–‰í•œ ê²ƒì€ ì•„ë‹ˆì—¬ì„œ ì˜ì€ ëª¨ë¥´ì§€ë§Œ JSP ê¸°ë°˜ backendë¥¼ ê³µë¶€í•œ ì ì´ ìˆìŠµë‹ˆë‹¤.<br/>
      ì´ ë•Œ, CSS, html, sql ë“±ì˜ ì›¹ì— ëŒ€í•´ ì¡°ê¸ˆì€ ìµí˜”ìŠµë‹ˆë‹¤.<br/>
      ì•„ì§ì€ ì˜ ëª¨ë¥´ëŠ” ê²ƒë“¤ì´ ë§ì§€ë§Œ ê¾¸ì¤€íˆ ì„±ì¥í•´ë‚˜ê°€ëŠ” ì£¼ë‹ˆì–´ ê°œë°œìê°€ ë˜ê³  ì‹¶ìŠµë‹ˆë‹¤.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
